// ─── AI Proxy Gateway — CSV Export Library ────────────────────────────────────
// RFC-4180 compliant. BOM prefix ensures Excel opens UTF-8 files correctly.

function csvCell(value: any): string {
  if (value === null || value === undefined) return '""';
  const str = String(value).replace(/"/g, '""');
  return `"${str}"`;
}

function csvRow(values: any[]): string {
  return values.map(csvCell).join(",");
}

function exportedAt(): string {
  return new Date().toLocaleString("id-ID", {
    timeZone: "Asia/Jakarta",
    day: "2-digit", month: "long", year: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
    hour12: false,
  }) + " WIB";
}

/** Format a number with thousand separators */
function fmtNum(v: any): string {
  const n = Number(v);
  if (isNaN(n)) return String(v ?? "");
  return n.toLocaleString("en-US");
}

/** Format cost: micro-dollars → $X.XXXXX */
function fmtCost(v: any): string {
  const n = Number(v);
  if (isNaN(n) || n === 0) return "$0.00";
  return "$" + (n / 1_000_000).toFixed(5);
}

/** Format latency ms */
function fmtMs(v: any): string {
  const n = Number(v);
  if (isNaN(n)) return "";
  return n >= 1000 ? `${(n / 1000).toFixed(2)}s` : `${n}ms`;
}

export interface CsvSection {
  title: string;
  headers: string[];
  rows: any[][];
  notes?: string;
}

export interface CsvExportOptions {
  sections: CsvSection[];
  filename: string;
  /** e.g. "Today", "Last 7 Days", "Last 30 Days", "All Time" */
  periodLabel?: string;
  keyName?: string;
}

// ─── Core engine ───────────────────────────────────────────────────────────────

function buildCsv(options: CsvExportOptions): string {
  const { sections, periodLabel, keyName } = options;
  const lines: string[] = [];

  // ── Report header ────────────────────────────────────────────────────────────
  lines.push(csvRow(["╔══════════════════════════════════════════════════════════╗"]));
  lines.push(csvRow(["  AI Proxy Gateway — Export Report"]));
  lines.push(csvRow(["╚══════════════════════════════════════════════════════════╝"]));
  lines.push("");
  lines.push(csvRow(["Exported At", exportedAt()]));
  if (keyName)     lines.push(csvRow(["API Key", keyName]));
  if (periodLabel) lines.push(csvRow(["Period", periodLabel]));
  lines.push(csvRow(["Sections", String(sections.length)]));
  lines.push("");

  // ── Sections ─────────────────────────────────────────────────────────────────
  for (let i = 0; i < sections.length; i++) {
    const sec = sections[i];
    lines.push(csvRow([`── Section ${i + 1}: ${sec.title} ──`]));
    if (sec.notes) lines.push(csvRow(["Note", sec.notes]));
    lines.push(csvRow([`Rows`, String(sec.rows.length), `Columns`, String(sec.headers.length)]));
    lines.push(csvRow(sec.headers));
    for (const row of sec.rows) lines.push(csvRow(row));
    lines.push("");
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push(csvRow(["── End of Report ──"]));
  lines.push(csvRow(["Generated by AI Proxy Gateway Dashboard", exportedAt()]));

  return "\uFEFF" + lines.join("\n");
}

function download(csv: string, filename: string) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : filename + ".csv";
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Public API ────────────────────────────────────────────────────────────────

export function exportCsvMultiSection(
  sections: CsvSection[],
  filename: string,
  periodLabel?: string,
  keyName?: string,
) {
  download(buildCsv({ sections, filename, periodLabel, keyName }), filename);
}

export function exportCsvSimple(
  headers: string[],
  rows: any[][],
  filename: string,
  periodLabel?: string,
  keyName?: string,
) {
  exportCsvMultiSection(
    [{ title: filename.replace(/[-_]/g, " ").replace(/\.csv$/i, ""), headers, rows }],
    filename + ".csv",
    periodLabel,
    keyName,
  );
}

// ─── Section builders ─────────────────────────────────────────────────────────

/** Build a stats summary section from period stats objects */
export function buildStatsSummarySection(
  periods: { label: string; data: Record<string, number> }[],
  title = "Summary Statistics",
): CsvSection {
  const metricKeys = Object.keys(periods[0]?.data || {});
  const headers = ["Metric", ...periods.map(p => p.label)];
  const rows = metricKeys.map(k => {
    const label = k
      .replace(/([A-Z])/g, " $1")
      .replace(/^./, s => s.toUpperCase());
    return [
      label,
      ...periods.map(p => {
        const v = p.data[k];
        if (k.toLowerCase().includes("cost")) return fmtCost(v);
        if (k.toLowerCase().includes("tokens") || k.toLowerCase().includes("requests")) return fmtNum(v);
        return v ?? 0;
      }),
    ];
  });
  return { title, headers, rows, notes: "Values shown per period column" };
}

/** Build request logs section with all useful columns */
export function buildLogsSection(logs: any[], title = "Request Logs"): CsvSection {
  return {
    title,
    notes: "is_counted = 1 means a user prompt was counted (not an IDE retry/sub-agent)",
    headers: [
      "Timestamp", "Model", "Provider", "IDE", "OS", "IP Address",
      "Session ID", "Context Event", "Input Tokens", "Output Tokens",
      "Total Tokens", "Context Tokens", "Est. Cost", "Latency",
      "Status", "Is Counted", "User Preview",
    ],
    rows: logs.map(l => [
      l.createdAt,
      l.model || "",
      l.provider || "",
      l.ideDetected || "",
      l.osDetected || "",
      l.ipAddress || "",
      l.sessionId || "",
      l.contextEvent || "",
      fmtNum(l.promptTokens),
      fmtNum(l.completionTokens),
      fmtNum(l.totalTokens),
      fmtNum(l.contextTokensBefore ?? l.estimatedContextLength ?? 0),
      fmtCost(l.estimatedCost),
      fmtMs(l.latencyMs),
      l.statusCode || "",
      l.isCountedRequest ? "Yes" : "No",
      String(l.requestPreview || "").slice(0, 200),
    ]),
  };
}

/** Build sessions section */
export function buildSessionsSection(sessions: any[], title = "Chat Sessions"): CsvSection {
  return {
    title,
    notes: "Each row represents one conversation session",
    headers: [
      "Session Name", "Session ID", "Device (short)", "IDE", "Model",
      "User Prompts", "Total Tokens", "Est. Cost", "First Seen", "Last Seen",
    ],
    rows: sessions.map(s => [
      s.sessionName || "Untitled Chat",
      s.sessionId || "",
      s.deviceFingerprint ? s.deviceFingerprint.substring(0, 12) + "…" : "",
      s.ideDetected || "",
      s.model || "",
      fmtNum(s.requestCount),
      fmtNum(s.totalTokens),
      fmtCost(s.estimatedCost),
      s.firstSeenAt || "",
      s.lastSeenAt || "",
    ]),
  };
}

/** Build models section */
export function buildModelsSection(models: any[], title = "Models by Usage"): CsvSection {
  return {
    title,
    headers: ["Model", "Requests", "Total Tokens", "Input Tokens", "Output Tokens", "Est. Cost", "Avg Latency"],
    rows: models.map(m => [
      m.model || "",
      fmtNum(m.requests ?? m.count),
      fmtNum(m.tokens),
      fmtNum(m.promptTokens ?? ""),
      fmtNum(m.completionTokens ?? ""),
      fmtCost(m.estimatedCost),
      m.avgLatency ? fmtMs(m.avgLatency) : "",
    ]),
  };
}

/** Build timeline section (for SessionDetailPage) */
export function buildTimelineSection(turns: any[], title = "Conversation Timeline"): CsvSection {
  return {
    title,
    notes: "Each row is one collapsed turn (multiple attempts deduplicated)",
    headers: [
      "Turn #", "Timestamp", "Model", "Context Event", "Tools Used",
      "Input Tokens", "Output Tokens", "Total Tokens", "Est. Cost",
      "Latency", "Status", "Attempts", "User Prompt", "Assistant Reply",
    ],
    rows: turns.map((t, i) => [
      i + 1,
      t.lastSeenAt || t.createdAt || "",
      t.model || "",
      t.contextEvent || "append",
      (t.toolsUsed || []).join(" | "),
      fmtNum(t.promptTokens),
      fmtNum(t.completionTokens),
      fmtNum(t.totalTokens),
      fmtCost(t.estimatedCost),
      fmtMs(t.latencyMs),
      t.statusCode || "",
      t.attemptCount || 1,
      String(t.requestPreview || "").slice(0, 300),
      String(t.responsePreview || "").slice(0, 300),
    ]),
  };
}
