// Lightweight RFC-4180 compliant CSV helper.
// BOM prefix ensures Excel opens UTF-8 files correctly.

function csvCell(value: any): string {
  const str = String(value ?? "").replace(/"/g, '""');
  return `"${str}"`;
}

function csvRow(values: any[]): string {
  return values.map(csvCell).join(",");
}

export interface CsvSection {
  title: string;
  headers: string[];
  rows: any[][];
  notes?: string;
}

export interface CsvExportOptions {
  sections: CsvSection[];
  filename: string;
  /** Human-readable period label e.g. "Today", "Last 7 Days", "Last 30 Days", "All Time" */
  periodLabel?: string;
  filters?: Record<string, string>;
}

function exportedAtStr(): string {
  return new Date().toLocaleString("id-ID", {
    timeZone: "Asia/Jakarta",
    day: "2-digit", month: "2-digit", year: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
    hour12: false,
  }) + " WIB";
}

/** Full export with metadata header, one or more sections with column descriptions */
export function exportCsvMultiSection(
  sections: CsvSection[],
  filename: string,
  periodLabel?: string,
) {
  const lines: string[] = [];

  // ─── Report metadata ────────────────────────────────────────────────────────
  lines.push(csvRow(["=== AI Proxy Gateway — Export Report ==="]));
  lines.push(csvRow(["Exported At", exportedAtStr()]));
  if (periodLabel) lines.push(csvRow(["Period", periodLabel]));
  lines.push(csvRow(["Total Sections", String(sections.length)]));
  lines.push("");

  // ─── Sections ───────────────────────────────────────────────────────────────
  for (const section of sections) {
    lines.push(csvRow([`[${section.title}]`]));
    if (section.notes) lines.push(csvRow(["Note", section.notes]));
    lines.push(csvRow([`Rows: ${section.rows.length}`]));
    lines.push(csvRow(section.headers));
    for (const row of section.rows) {
      lines.push(csvRow(row));
    }
    lines.push("");
  }

  // ─── Footer ─────────────────────────────────────────────────────────────────
  lines.push(csvRow(["=== End of Report ==="]));
  lines.push(csvRow(["Generated by AI Proxy Gateway Dashboard"]));

  _download(lines.join("\n"), filename);
}

/** Simple one-section export */
export function exportCsvSimple(
  headers: string[],
  rows: any[][],
  filename: string,
  periodLabel?: string,
) {
  exportCsvMultiSection(
    [{ title: filename, headers, rows }],
    filename + ".csv",
    periodLabel,
  );
}

function _download(csv: string, filename: string) {
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
